name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CallDelayedFunctions/Makefile
      run: make -C CallDelayedFunctions
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: CallDelayedFunctions/CallDelayedFunctions.dll
